[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "9.0.0"
  CI = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
